version: '3.7'

x-app_environment: &app_environment
  environment:
    - CALENDAR_HOST
    - CALENDAR_PORT
    - DB_DSN
    - GOPATH
    - GOBIN
    - GO111MODULE

x-worker_env: &worker_env
  environment:
    - DB_DSN
    - AMQP_DSN
    - QUEUE_NAME
    - PERIOD_CLEAR_MINUTE

services:
  # Эмулирование работы пльзователя
  client:
    build:
      context: ./calendar
    restart: "no"
    volumes:
      - ./calendar:/app:cached
    depends_on:
      - db
    command: wait-for server:8000 -t 10 -- go run main.go client
    links:
      - db
    <<: *app_environment
