version: '3.7'

x-app_environment: &app_environment
  environment:
    - CALENDAR_HOST
    - CALENDAR_PORT
    - DB_DSN
    - GOPATH
    - GOBIN
    - GO111MODULE

x-worker_env: &worker_env
  environment:
    - DB_DSN
    - AMQP_DSN
    - QUEUE_NAME
    - PERIOD_CLEAR_SECOND=3

services:
  server:
    build:
      context: ./calendar
    restart: unless-stopped
    volumes:
      - ./calendar:/app:cached
    depends_on:
      - db
    links:
      - db
    command: wait-for db:5432 -t 60 -- go run main.go server
    expose:
      - "8000"
    ports:
      - "8000:8000"
    <<: *app_environment

  # Планировщик
  scheduler:
    build:
      context: ./calendar
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./calendar:/app:cached
    command: wait-for rabbitmq:5672 -t 60 -- go run main.go scheduler
    links:
      - db
      - rabbitmq
    <<: *worker_env

  # Рассыльщик
  mailing:
    build:
      context: ./calendar
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./calendar:/app:cached
    command: wait-for rabbitmq:5672 -t 60 -- go run main.go mailing
    links:
      - db
      - rabbitmq
    <<: *worker_env


  rabbitmq:
    image: 'rabbitmq:3.7.17-management'
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
    volumes:
      - ./rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbit.config:/etc/rabbitmq/rabbitmq.config:ro

  db:
    image: postgres:11-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 15145:5432
