version: '3.7'

x-app_environment: &app_environment
  environment:
    - CALENDAR_HOST
    - CALENDAR_PORT
    - GOPATH
    - GOBIN
    - GO111MODULE

services:
  server:
    build:
      context: ./calendar
    restart: unless-stopped
    volumes:
      - ./calendar:/app:cached
    depends_on:
      - db
    links:
      - db
    command: go run main.go grpc_server
    expose:
      - "8000"
    ports:
      - "8000:8000"
    <<: *app_environment

  client:
    build:
      context: ./calendar
    restart: "no"
    volumes:
      - ./calendar:/app:cached
    depends_on:
      - db
    command: go run main.go grpc_client
    links:
      - db
    <<: *app_environment


  rabbitmq:
    image: 'rabbitmq:latest'

  db:
    image: postgres:11-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 15145:5432
  
  worker:
    build:
      context: ./background_workers
    restart: unless-stopped
    volumes:
      - ./background_workers:/app:cached
    depends_on:
      - db
      - rabbitmq
    command: go run main.go